# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
imports:
    - { resource: "@AppBundle/Resources/config/services.yml" }

parameters:
    parsermarkdown.urlReadme: https://raw.githubusercontent.com/Emergya/SymfonyZero/master/README.md


services:
    fos_user.doctrine_registry:
        alias: doctrine
    parsermarkdown:
        class:      AppBundle\Services\ParserMarkdown
        arguments:  [%parsermarkdown.urlReadme%]
