parameters:
    symfonyzero.user.repository.class: AppBundle\Repository\UserRepository

services:
    symfonyzero.user.repository:
        class: %symfonyzero.user.repository.class%
        public: true
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [ AppBundle\Entity\User ]