imports:
    - { resource: repositories.yml }
    - { resource: managers.yml }

services:
    symfonyzero.email:
        class:  AppBundle\Services\Email
        arguments: ['@swiftmailer.mailer', '@templating', '%mailer_user%']
    symfonyzero.provider.oauth:
        class:  AppBundle\Security\FOSUBUserProvider
        arguments: ['@fos_user.user_manager', { google: google_id }]
    user.registration.form.type:
        class: AppBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: user_registration }
